# -*- coding: utf-8 -*-
"""AppDC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j7E90fIIJNLtc0vmJQH11Lgg2i2J4qgu
"""

import streamlit as st
import numpy as np
import joblib
import pandas as pd # Added for DataFrame handling
from sklearn.ensemble import RandomForestClassifier # Added for model training

# Title
st.set_page_config(page_title="Fraud Detection App", layout="centered")

st.title("💳 Fraud Detection App")
st.write("Enter transaction details below to check if it's fraud or not.")

# Load your trained model (IMPORTANT: model.pkl hona chahiye)
try:
    model = joblib.load("Fraud_Analysis_Dataset.pkl")
except FileNotFoundError:
    st.warning("Model file not found. Training a new model and saving it. This might take a moment.")

    # Load raw data
    df_raw = pd.read_csv("Fraud_Analysis_Dataset.csv")

    # Prepare features (X) and target (y) to match Streamlit inputs
    # Drop 'isFraud' for features
    X_prep = df_raw.drop("isFraud", axis=1)
    y_prep = df_raw["isFraud"]

    # Drop non-numeric and irrelevant columns that are not in Streamlit inputs
    X_prep = X_prep.drop(['nameOrig', 'nameDest', 'step'], axis=1)

    # Apply the same manual type encoding used in Streamlit app
    type_mapping_for_training = {
        "CASH_IN": 0,
        "CASH_OUT": 1,
        "DEBIT": 2,
        "PAYMENT": 3,
        "TRANSFER": 4
    }
    X_prep['type'] = X_prep['type'].map(type_mapping_for_training)

    # Define the exact features that the Streamlit app collects inputs for
    # (amount, oldbalanceOrg, newbalanceOrig, oldbalanceDest, newbalanceDest, type_encoded)
    # Ensure the order matches the prediction input later
    feature_cols = [
        'type', 'amount', 'oldbalanceOrg', 'newbalanceOrig',
        'oldbalanceDest', 'newbalanceDest'
    ]
    X_model_train = X_prep[feature_cols]

    # Train the RandomForestClassifier
    model = RandomForestClassifier(random_state=42) # Added random_state for reproducibility
    model.fit(X_model_train, y_prep)

    # Save the trained model
    joblib.dump(model, "Fraud_Analysis_Dataset.pkl")
    st.success("Model trained and saved as 'Fraud_Analysis_Dataset.pkl'.")

# Input Fields
amount = st.number_input("Transaction Amount", min_value=0.0, value=0.0)

oldbalanceOrg = st.number_input("Old Balance (Origin)", min_value=0.0, value=0.0)
newbalanceOrig = st.number_input("New Balance (Origin)", min_value=0.0, value=0.0)

oldbalanceDest = st.number_input("Old Balance (Destination)", min_value=0.0, value=0.0)
newbalanceDest = st.number_input("New Balance (Destination)", min_value=0.0, value=0.0)

# Transaction Type
type_options = ["CASH_IN", "CASH_OUT", "DEBIT", "PAYMENT", "TRANSFER"]
type_selected = st.selectbox("Transaction Type", type_options)

# Encode type manually (same as training)
type_mapping = {
    "CASH_IN": 0,
    "CASH_OUT": 1,
    "DEBIT": 2,
    "PAYMENT": 3,
    "TRANSFER": 4
}

type_encoded = type_mapping[type_selected]

# Prediction Button
if st.button("Check Fraud"):

    # Create input array (same order as training data for the 6 features)
    input_data = np.array([[
        type_encoded,
        amount,
        oldbalanceOrg,
        newbalanceOrig,
        oldbalanceDest,
        newbalanceDest
    ]])

    prediction = model.predict(input_data)

    if prediction[0] == 1:
        st.error("⚠️ Fraud Transaction Detected!")
    else:
        st.success("✅ Legitimate Transaction")

